// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Datalock validation fails for different reasons")]
    public partial class DatalockValidationFailsForDifferentReasonsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "datalock_errors.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Datalock validation fails for different reasons", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the UKPRN then d" +
            "atalock DLOCK_01 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheUKPRNThenDatalockDLOCK_01WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the UKPRN then d" +
                    "atalock DLOCK_01 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table258 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table258.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 10
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table258, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table259 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table259.AddRow(new string[] {
                        "1000000",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 15
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table259, "When ");
#line 20
    testRunner.Then("a datalock error DLOCK_01 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the ULN then dat" +
            "alock DLOCK_02 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheULNThenDatalockDLOCK_02WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the ULN then dat" +
                    "alock DLOCK_02 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table260 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table260.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 24
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table260, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table261 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table261.AddRow(new string[] {
                        "9999999",
                        "3456",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 29
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table261, "When ");
#line 34
    testRunner.Then("a datalock error DLOCK_02 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the standard cod" +
            "e then datalock DLOCK_03 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheStandardCodeThenDatalockDLOCK_03WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the standard cod" +
                    "e then datalock DLOCK_03 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table262 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table262.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 38
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table262, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table263 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table263.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "2",
                        "10000",
                        "01/05/2017"});
#line 43
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table263, "When ");
#line 48
    testRunner.Then("a datalock error DLOCK_03 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the framework co" +
            "de then datalock DLOCK_04 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheFrameworkCodeThenDatalockDLOCK_04WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the framework co" +
                    "de then datalock DLOCK_04 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table264 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table264.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 54
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table264, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table265 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table265.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "451",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 59
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table265, "When ");
#line 64
    testRunner.Then("a datalock error DLOCK_04 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the programme ty" +
            "pe then datalock DLOCK_05 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheProgrammeTypeThenDatalockDLOCK_05WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the programme ty" +
                    "pe then datalock DLOCK_05 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 67
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table266 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table266.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 69
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table266, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table267 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table267.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "3",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 74
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table267, "When ");
#line 79
    testRunner.Then("a datalock error DLOCK_05 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for the pathway code" +
            " then datalock DLOCK_06 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForThePathwayCodeThenDatalockDLOCK_06WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for the pathway code" +
                    " then datalock DLOCK_06 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 82
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table268 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table268.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 84
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table268, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table269 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table269.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "2",
                        "10000",
                        "01/05/2017"});
#line 89
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table269, "When ");
#line 94
    testRunner.Then("a datalock error DLOCK_06 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When no matching record found in an employer digital account for for the agreed p" +
            "rice then datalock DLOCK_07 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForForTheAgreedPriceThenDatalockDLOCK_07WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When no matching record found in an employer digital account for for the agreed p" +
                    "rice then datalock DLOCK_07 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 97
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table270 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table270.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 99
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table270, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table271 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table271.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10010",
                        "01/05/2017"});
#line 104
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table271, "When ");
#line 109
    testRunner.Then("a datalock error DLOCK_07 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When there is more than one matching commitment in the employer digital account t" +
            "hen datalock DLOCK_08 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenThereIsMoreThanOneMatchingCommitmentInTheEmployerDigitalAccountThenDatalockDLOCK_08WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When there is more than one matching commitment in the employer digital account t" +
                    "hen datalock DLOCK_08 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 113
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table272 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table272.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
            table272.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 115
    testRunner.Given("the following commitments exist for an apprentice:", ((string)(null)), table272, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table273 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table273.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 121
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table273, "When ");
#line 126
    testRunner.Then("a datalock error DLOCK_08 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When the start month recorded in the employer digital account is after the start " +
            "month in the ILR then datalock DLOCK_09 will be produced")]
        [NUnit.Framework.CategoryAttribute("ILRSubmissionDataLockErrors")]
        public virtual void WhenTheStartMonthRecordedInTheEmployerDigitalAccountIsAfterTheStartMonthInTheILRThenDatalockDLOCK_09WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When the start month recorded in the employer digital account is after the start " +
                    "month in the ILR then datalock DLOCK_09 will be produced", new string[] {
                        "ILRSubmissionDataLockErrors"});
#line 130
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table274 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table274.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 132
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table274, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table275 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table275.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "30/04/2017"});
#line 137
    testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table275, "When ");
#line 142
    testRunner.Then("a datalock error DLOCK_09 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record is found in an employer " +
            "digital account for the UKPRN then datalock DLOCK_01 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordIsFoundInAnEmployerDigitalAccountForTheUKPRNThenDatalockDLOCK_01WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record is found in an employer " +
                    "digital account for the UKPRN then datalock DLOCK_01 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 150
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table276 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table276.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 152
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table276, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table277 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table277.AddRow(new string[] {
                        "1000000",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 157
    testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table277, "When ");
#line 162
    testRunner.Then("a datalock error DLOCK_01 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for the ULN then datalock DLOCK_02 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForTheULNThenDatalockDLOCK_02WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for the ULN then datalock DLOCK_02 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 165
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table278 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table278.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 167
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table278, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table279 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table279.AddRow(new string[] {
                        "9999999",
                        "3456",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 172
    testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table279, "When ");
#line 177
    testRunner.Then("a datalock error DLOCK_02 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for the standard code then datalock DLOCK_03 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForTheStandardCodeThenDatalockDLOCK_03WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for the standard code then datalock DLOCK_03 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 180
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table280 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table280.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 182
      testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table280, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table281 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "standard code",
                        "agreed price",
                        "start date"});
            table281.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "2",
                        "10000",
                        "01/05/2017"});
#line 187
   testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table281, "When ");
#line 192
    testRunner.Then("a datalock error DLOCK_03 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for the framework code then datalock DLOCK_04 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForTheFrameworkCodeThenDatalockDLOCK_04WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for the framework code then datalock DLOCK_04 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 197
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table282 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table282.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 199
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table282, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table283 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table283.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "451",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 204
    testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table283, "When ");
#line 209
    testRunner.Then("a datalock error DLOCK_04 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for the programme type then datalock DLOCK_05 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForTheProgrammeTypeThenDatalockDLOCK_05WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for the programme type then datalock DLOCK_05 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 212
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table284 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table284.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 214
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table284, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table285 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table285.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "3",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 219
    testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table285, "When ");
#line 224
    testRunner.Then("a datalock error DLOCK_05 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for the pathway code then datalock DLOCK_06 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForThePathwayCodeThenDatalockDLOCK_06WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for the pathway code then datalock DLOCK_06 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 227
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table286 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table286.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 229
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table286, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table287 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table287.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "2",
                        "10000",
                        "01/05/2017"});
#line 234
     testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table287, "When ");
#line 239
    testRunner.Then("a datalock error DLOCK_06 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and no matching record found in an employer dig" +
            "ital account for for the agreed price then datalock DLOCK_07 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndNoMatchingRecordFoundInAnEmployerDigitalAccountForForTheAgreedPriceThenDatalockDLOCK_07WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and no matching record found in an employer dig" +
                    "ital account for for the agreed price then datalock DLOCK_07 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 242
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table288 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table288.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 244
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table288, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table289 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table289.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10001",
                        "01/05/2017"});
#line 249
     testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table289, "When ");
#line 254
    testRunner.Then("a datalock error DLOCK_07 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and there is more than one matching commitment " +
            "in the employer digital account then datalock DLOCK_08 will be produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndThereIsMoreThanOneMatchingCommitmentInTheEmployerDigitalAccountThenDatalockDLOCK_08WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and there is more than one matching commitment " +
                    "in the employer digital account then datalock DLOCK_08 will be produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 258
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table290 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table290.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
            table290.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 260
    testRunner.Given("the following commitments exist for an apprentice:", ((string)(null)), table290, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table291 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table291.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 266
     testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table291, "When ");
#line 271
    testRunner.Then("a datalock error DLOCK_08 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When monthly payment process runs and the start month recorded in the employer di" +
            "gital account is after the start month in the ILR then datalock DLOCK_09 will be" +
            " produced")]
        [NUnit.Framework.CategoryAttribute("PeriodEndDataLockErrors")]
        public virtual void WhenMonthlyPaymentProcessRunsAndTheStartMonthRecordedInTheEmployerDigitalAccountIsAfterTheStartMonthInTheILRThenDatalockDLOCK_09WillBeProduced()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When monthly payment process runs and the start month recorded in the employer di" +
                    "gital account is after the start month in the ILR then datalock DLOCK_09 will be" +
                    " produced", new string[] {
                        "PeriodEndDataLockErrors"});
#line 275
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table292 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table292.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "01/05/2017"});
#line 277
    testRunner.Given("the following commitment exists for an apprentice:", ((string)(null)), table292, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table293 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date"});
            table293.AddRow(new string[] {
                        "9999999",
                        "1234",
                        "450",
                        "2",
                        "1",
                        "10000",
                        "30/04/2017"});
#line 282
     testRunner.When("monthly payment process runs for the following ILR data:", ((string)(null)), table293, "When ");
#line 287
    testRunner.Then("a datalock error DLOCK_09 is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
