// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Amount due is calculated based on previously earned amount")]
    public partial class AmountDueIsCalculatedBasedOnPreviouslyEarnedAmountFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "earnings_calc.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Amount due is calculated based on previously earned amount", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculating payments due")]
        [NUnit.Framework.CategoryAttribute("EarningsDistribution")]
        [NUnit.Framework.TestCaseAttribute("0", "1000", "1000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("500", "1000", "500", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1000", "1000", "0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("0", "0", "0", new string[0])]
        public virtual void CalculatingPaymentsDue(string previousAmount, string earnedAmount, string dueAmount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EarningsDistribution"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculating payments due", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
testRunner.Given(string.Format("a provider has previously earned {0} in period R01", previousAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
testRunner.When(string.Format("an earning of {0} is calculated for period R01", earnedAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
testRunner.Then(string.Format("a payment of {0} is due", dueAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings distribution")]
        [NUnit.Framework.CategoryAttribute("EarningsDistribution")]
        [NUnit.Framework.TestCaseAttribute("15000", "12", "1000", "3000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15000", "6", "2000", "3000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "12", "500", "1500", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "6", "1000", "1500", new string[0])]
        public virtual void EarningsDistribution(string agreedPrice, string censusMonths, string monthlyEarnings, string completionPayment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EarningsDistribution"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings distribution", @__tags);
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
testRunner.When(string.Format("the planned course duration covers {0} months", censusMonths), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
testRunner.And(string.Format("there is an agreed price of {0}", agreedPrice), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
testRunner.Then(string.Format("the monthly earnings is {0}", monthlyEarnings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
testRunner.And(string.Format("the completion payment is {0}", completionPayment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings distribution when learner finishes early or late")]
        [NUnit.Framework.CategoryAttribute("EarningsDistribution")]
        [NUnit.Framework.TestCaseAttribute("15000", "early", "12", "8", "1000", "3000", "4000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15000", "early", "6", "5", "2000", "3000", "2000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "early", "12", "9", "500", "1500", "1500", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "early", "6", "4", "1000", "1500", "2000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15000", "late", "12", "16", "1000", "3000", "0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15000", "late", "6", "7", "2000", "3000", "0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "late", "12", "15", "500", "1500", "0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7500", "late", "6", "8", "1000", "1500", "0", new string[0])]
        public virtual void EarningsDistributionWhenLearnerFinishesEarlyOrLate(string agreedPrice, string earlyLate, string plannedCensusMonths, string actualCensusMonthsInLearning, string monthlyEarnings, string completionPayment, string balancingPayment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EarningsDistribution"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings distribution when learner finishes early or late", @__tags);
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
testRunner.When(string.Format("the planned course duration covers {0} months", plannedCensusMonths), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
testRunner.And(string.Format("the actual duration of learning is {0} months", actualCensusMonthsInLearning), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
testRunner.And(string.Format("there is an agreed price of {0}", agreedPrice), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
testRunner.Then(string.Format("the monthly earnings is {0}", monthlyEarnings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
testRunner.And(string.Format("the completion payment is {0}", completionPayment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
testRunner.And(string.Format("the balancing payment is {0}", balancingPayment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
