// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("2 learners, paid in priority order")]
    public partial class _2LearnersPaidInPriorityOrderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "two_learners_paid_in_priority.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "2 learners, paid in priority order", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
    #line 4
        testRunner.Given("Two learners are programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
        testRunner.And("the apprenticeship funding band maximum for each learner is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
            "vailable for both learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndAvailableForBothLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
                    "vailable for both learners", ((string[])(null)));
#line 7
    this.ScenarioSetup(scenarioInfo);
#line 3
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table538 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table538.AddRow(new string[] {
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000"});
#line 8
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table538, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table539 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table539.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table539.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 11
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table539, "And ");
#line hidden
            TechTalk.SpecFlow.Table table540 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table540.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table540.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 15
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table540, "When ");
#line hidden
            TechTalk.SpecFlow.Table table541 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table541.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table541.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table541.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table541.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table541.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table541.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table541.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table541.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table541.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 19
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table541, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table542 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table542.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table542.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table542.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table542.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table542.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table542.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table542.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table542.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table542.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 30
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table542, "And ");
#line hidden
            TechTalk.SpecFlow.Table table543 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table543.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table543.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table543.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table543.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table543.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table543.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table543.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table543.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table543.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 41
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table543, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
            "s available for one learner only")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndIsAvailableForOneLearnerOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
                    "s available for one learner only", ((string[])(null)));
#line 54
    this.ScenarioSetup(scenarioInfo);
#line 3
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table544 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table544.AddRow(new string[] {
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
#line 55
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table544, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table545 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table545.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table545.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 58
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table545, "And ");
#line hidden
            TechTalk.SpecFlow.Table table546 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table546.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table546.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 62
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table546, "When ");
#line hidden
            TechTalk.SpecFlow.Table table547 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table547.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table547.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table547.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table547.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table547.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table547.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table547.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table547.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table547.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 66
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table547, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table548 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table548.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table548.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table548.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table548.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "900"});
            table548.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table548.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table548.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table548.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table548.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 77
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table548, "And ");
#line hidden
            TechTalk.SpecFlow.Table table549 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table549.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table549.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1900",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "0"});
            table549.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table549.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "1900"});
            table549.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table549.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table549.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table549.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table549.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 88
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table549, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
            "here is enough levy to fund one and a half learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndThereIsEnoughLevyToFundOneAndAHalfLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
                    "here is enough levy to fund one and a half learners", ((string[])(null)));
#line 101
    this.ScenarioSetup(scenarioInfo);
#line 3
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table550 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table550.AddRow(new string[] {
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500"});
#line 102
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table550, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table551 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table551.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table551.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 105
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table551, "And ");
#line hidden
            TechTalk.SpecFlow.Table table552 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table552.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table552.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 109
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table552, "When ");
#line hidden
            TechTalk.SpecFlow.Table table553 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table553.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table553.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table553.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table553.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table553.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table553.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table553.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table553.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table553.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 113
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table553, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table554 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table554.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table554.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "950",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "0"});
            table554.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table554.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "950"});
            table554.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table554.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "500"});
            table554.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "500",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "0"});
            table554.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table554.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 124
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table554, "And ");
#line hidden
            TechTalk.SpecFlow.Table table555 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table555.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table555.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1950",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "0"});
            table555.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table555.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "1950"});
            table555.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table555.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "1500"});
            table555.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "0"});
            table555.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table555.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 135
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table555, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
