// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("2 learners, paid in priority order")]
    [NUnit.Framework.CategoryAttribute("LearnersPaidInPriority")]
    public partial class _2LearnersPaidInPriorityOrderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "two_learners_paid_in_priority.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "2 learners, paid in priority order", null, ProgrammingLanguage.CSharp, new string[] {
                        "LearnersPaidInPriority"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
    #line 5
        testRunner.Given("Two learners are programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
        testRunner.And("the apprenticeship funding band maximum for each learner is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
            "vailable for both learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndAvailableForBothLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
                    "vailable for both learners", ((string[])(null)));
#line 8
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table759 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table759.AddRow(new string[] {
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000"});
#line 9
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table759, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table760 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table760.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table760.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 12
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table760, "And ");
#line hidden
            TechTalk.SpecFlow.Table table761 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table761.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table761.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 16
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table761, "When ");
#line hidden
            TechTalk.SpecFlow.Table table762 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table762.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table762.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table762.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table762.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table762.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table762.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table762.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table762.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table762.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 20
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table762, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table763 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table763.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table763.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table763.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table763.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table763.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table763.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table763.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table763.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table763.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 31
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table763, "And ");
#line hidden
            TechTalk.SpecFlow.Table table764 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table764.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table764.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table764.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table764.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 42
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table764, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
            "s available for one learner only")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndIsAvailableForOneLearnerOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
                    "s available for one learner only", ((string[])(null)));
#line 55
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table765 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table765.AddRow(new string[] {
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
#line 56
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table765, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table766 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table766.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table766.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 59
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table766, "And ");
#line hidden
            TechTalk.SpecFlow.Table table767 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table767.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table767.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 63
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table767, "When ");
#line hidden
            TechTalk.SpecFlow.Table table768 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table768.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table768.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table768.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table768.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table768.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table768.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table768.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table768.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table768.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 67
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table768, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table769 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table769.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table769.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table769.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table769.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "900"});
            table769.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table769.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table769.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table769.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table769.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 78
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table769, "And ");
#line hidden
            TechTalk.SpecFlow.Table table770 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table770.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table770.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1900",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "0"});
            table770.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table770.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "1900"});
            table770.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table770.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table770.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table770.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table770.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 89
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table770, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
            "here is enough levy to fund one and a half learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndThereIsEnoughLevyToFundOneAndAHalfLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
                    "here is enough levy to fund one and a half learners", ((string[])(null)));
#line 102
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table771 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table771.AddRow(new string[] {
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500"});
#line 103
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table771, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table772 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table772.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table772.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 106
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table772, "And ");
#line hidden
            TechTalk.SpecFlow.Table table773 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table773.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table773.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 110
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table773, "When ");
#line hidden
            TechTalk.SpecFlow.Table table774 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table774.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table774.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table774.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table774.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table774.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table774.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table774.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table774.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table774.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 114
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table774, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table775 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table775.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table775.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "950",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "0"});
            table775.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table775.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "950"});
            table775.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table775.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "500"});
            table775.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "500",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "0"});
            table775.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table775.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 125
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table775, "And ");
#line hidden
            TechTalk.SpecFlow.Table table776 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table776.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table776.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1950",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "0"});
            table776.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table776.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "1950"});
            table776.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table776.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "1500"});
            table776.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "0"});
            table776.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table776.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 136
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table776, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
